---
title: "K-12 School Shootings"
author: "Connor Rothschild"
date: "9/19/2019"
output: 
  html_document:
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(ggplot2)
library(tidyverse)
#devtools::install_github("connorrothschild/cr")
library(cr)
cr::set_cr_theme(font = "lato")
```

## Data

Data is from [the CHDS database](https://docs.google.com/spreadsheets/d/1HqbfMxnk9X3_mQvLyW_LEUe3Yyr7cXMPfwqUVfdq7sY/edit?usp=sharing), and cleaned in Excel.

```{r}
data <- read_excel("shootings_data.xlsx")

data <- data %>% 
  mutate(year = lubridate::year(date),
         month = lubridate::month(date))
```

## Initial Exploration

```{r}
summary(data$killed)
summary(data$wounded)
summary(data$total_inj_or_killed)

# top incident
subset(data,data$total_inj_or_killed==76)
```

Over time:

IDEA: Heatmap/Calendar map of shootings over time with month on x and year on 

```{r}
data %>%
  filter(time != "Unknown") %>% 
  mutate(day_of_week = fct_relevel(day_of_week, "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")) %>% 
  mutate(day_of_week = fct_rev(day_of_week)) %>% 
  group_by(day_of_week) %>% 
  ggplot(aes(day_of_week)) +
  geom_bar() +
  fix_bars() +
  coord_flip() +
  labs(title = "When do Shootings Occur?",
       subtitle = "By day of week", 
       x = "Day of Week", y = "Number of Incidents")
```

```{r}
data <- data %>%
  filter(time != "Unknown") %>% 
  mutate(new_time = ifelse(str_detect(time, " AM"), time, str_replace_all(time, " PM", ""))) %>% 
  mutate(new_time = ifelse(!str_detect(new_time, " AM"), str_replace_all(new_time, ":", ""), new_time)) %>% 
  mutate(new_time = ifelse(new_time != 1200 & !str_detect(new_time, "AM"), as.numeric(new_time)+1200, new_time)) %>% 
  mutate(new_time = str_replace_all(new_time, ":", "")) %>% 
  mutate(new_time = str_replace_all(new_time, " AM", "")) %>%
  mutate(new_time = as.numeric(new_time)) %>% 
  # round to nearest whole hour
  mutate(new_hour = round(new_time, -2)) 

data_w_time_emphasis <-
  data %>% 
  mutate(emphasis = ifelse(new_hour == "800", "8 AM",""))

data_w_time_emphasis %>% 
  group_by(new_hour) %>% 
  ggplot(aes(new_hour, fill = emphasis)) +
  geom_bar(width = 70, show.legend = FALSE) +
  annotate("label", x = 1000, y = 119, label = "8 AM") +
    labs(title = "When do Shootings Occur?",
         subtitle = "By time of day",
       x = element_blank(), y = "Number of Incidents") +
  scale_x_continuous(breaks = c(600,1200,1800), labels = c("6 AM","12 PM", "6 PM")) +
    fix_bars()
```

```{r}
col1 = "#49a09d"
col2 = "#5f2c82"

data %>%
  filter(time != "Unknown") %>% 
  mutate(day_of_week = fct_relevel(day_of_week, "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")) %>% 
  mutate(day_of_week = fct_rev(day_of_week)) %>% 
  mutate(new_time = ifelse(str_detect(time, " AM"), time, str_replace_all(time, " PM", ""))) %>% 
  mutate(new_time = ifelse(!str_detect(new_time, " AM"), str_replace_all(new_time, ":", ""), new_time)) %>% 
  mutate(new_time = ifelse(new_time != 1200 & !str_detect(new_time, "AM"), as.numeric(new_time)+1200, new_time)) %>% 
  mutate(new_time = str_replace_all(new_time, ":", "")) %>% 
  mutate(new_time = str_replace_all(new_time, " AM", "")) %>%
  mutate(new_time = as.numeric(new_time)) %>% 
  # round to nearest whole hour
  mutate(new_hour = round(new_time, -2)) %>% 
  group_by(new_hour, day_of_week) %>% 
  summarise(n = n()) %>% 
  filter(new_hour < 2400) %>% 
  ggplot(aes(new_hour, day_of_week)) + geom_tile(aes(fill = n), colour = "white", na.rm = TRUE) +
  ggplot2::scale_fill_gradient(low = col1, high = col2) +  
  guides(fill=guide_legend(title="Total Incidents")) +
  labs(title = "When do Shootings Occur?",
       subtitle = "By time and day of week", 
       x = "Time", y = "Day of Week") +
  scale_x_continuous(breaks = c(600,1200,1800), labels = c("6 AM","12 PM", "6 PM")) +
  drop_axis(axis = "both") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
data_w_emphasis <- 
  data %>% 
  mutate(emphasis = ifelse(year == 2018, "2018",""))

data_w_emphasis %>% 
  ggplot(aes(x=year, fill = emphasis)) +
  geom_bar(show.legend = FALSE) +
  annotate("label", x = 2015, y = 85, label = "2018") +
  labs(title = "Shootings per Year",
       x = "Year",
       y = "Number of Shootings") +
  fix_bars() +
  drop_axis(axis = "y")
```

```{r}
data %>% 
  mutate(month = as.factor(month)) %>% 
  mutate(month = fct_rev(month)) %>% 
  group_by(year,month) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(year, month)) + geom_tile(aes(fill = n),colour = "white") +
  #geom_label(data = subset(data, total_inj_or_killed > 60), aes(year, month, label = school)) +
  ggplot2::scale_fill_gradient(low = col1, high = col2) +  
  guides(fill=guide_legend(title="Total Incidents")) +
  labs(title = "When do Shootings Occur?",
       subtitle = "By Month and Year",
       x = "Year", y = "Month") + 
  scale_y_discrete(breaks = c(1:12), 
                   labels = c("January", "February", "March", "April", "May",
                              "June", "July", "August", "September", 
                              "October", "November", "December")) +
  scale_x_continuous(breaks = c(1970,1980,1990,2000,2010,2019)) +
  drop_axis() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
```


```{r}
data %>% 
  filter(!is.na(total_inj_or_killed)) %>% 
  mutate(month = as.factor(month)) %>% 
  mutate(month = fct_rev(month)) %>% 
  group_by(year, month) %>% 
  summarise(inj_and_killed = sum(total_inj_or_killed)) %>% 
  ggplot(aes(year, month)) + geom_tile(aes(fill = inj_and_killed),colour = "white") +
  #ggrepel::geom_text_repel(data = subset(data, school = "Cokeville Elementary School"), aes(label = school)) +
  ggplot2::scale_fill_gradient(low = col1, high = col2) +  
  guides(fill=guide_legend(title="Total Victims")) +
  labs(title = "Total Victims in K-12 School Shootings by Month and Year",
       subtitle = "Injured or Killed",
       x = "Year", y = "Month") + 
  scale_y_discrete(breaks = c(1:12), 
                   labels = c("January", "February", "March", "April", "May",
                              "June", "July", "August", "September", 
                              "October", "November", "December")) +
  scale_x_continuous(breaks = c(1970,1980,1990,2000,2010,2019)) +
  drop_axis() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

```

IDEA: gganimate of shootings over time on U.S. map.

Step 1: bring in lat/long coordinates from ggmap:
See: https://www.jessesadler.com/post/geocoding-with-r/

```{r}
loc_data <- data %>% 
  select(city, state)

library(localgeo)
lat_long <- localgeo::geocode(data$city, data$state)
  
data <- cbind(data, lat_long)
```

Step 2: draw bubbles, animate 
See: https://d4tagirl.com/2017/05/how-to-plot-animated-maps-with-gganimate

IDEA: rayshader of victims per state
